# Generated by Django 2.2.28 on 2024-03-13 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('pictures', models.ImageField(blank=True, upload_to='location_images')),
                ('about', models.CharField(max_length=500)),
                ('favourites', models.IntegerField()),
                ('reviewsAmount', models.IntegerField()),
                ('reviewsAverage', models.FloatField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('pictures', models.ImageField(blank=True, upload_to='profile_images')),
                ('experience', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField()),
                ('pictures', models.ImageField(blank=True, upload_to='spot_images')),
                ('postcode', models.CharField(max_length=8)),
                ('reviewsAmount', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.Location')),
            ],
            options={
                'verbose_name_plural': 'Spots',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('comment', models.TextField(max_length=500)),
                ('value', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=1)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.Spot')),
            ],
            options={
                'verbose_name': 'Spot Review',
                'verbose_name_plural': 'Spot Reviews',
                'ordering': ['-pub_date'],
            },
        ),
    ]
