# Generated by Django 2.2.28 on 2024-03-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='spot_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
