# Generated by Django 4.2.11 on 2024-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='postcode',
        ),
        migrations.AlterField(
            model_name='location',
            name='about',
            field=models.CharField(default='Default text :)', max_length=500),
        ),
    ]
