# Generated by Django 2.2.28 on 2024-03-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0002_auto_20240322_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pictures',
        ),
    ]
