# Generated by Django 2.2.28 on 2024-03-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0002_auto_20240314_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=12),
        ),
    ]
