# Generated by Django 2.2.28 on 2024-03-19 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gregssnorkelscores', '0002_auto_20240314_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='favourites',
        ),
        migrations.AddField(
            model_name='spot',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
