# Generated by Django 2.2.28 on 2024-03-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0003_remove_spot_favourites_alter_review_spot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Spot Review', 'verbose_name_plural': 'Spot Reviews'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='pub_date',
        ),
    ]
