# Generated by Django 2.2.28 on 2024-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0003_auto_20240319_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
