# Generated by Django 2.2.28 on 2024-03-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0004_auto_20240321_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.Spot'),
        ),
    ]
