# Generated by Django 2.2.28 on 2024-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0004_auto_20240319_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='about',
        ),
        migrations.RemoveField(
            model_name='location',
            name='author',
        ),
        migrations.RemoveField(
            model_name='location',
            name='reviewsAmount',
        ),
        migrations.RemoveField(
            model_name='location',
            name='reviewsAverage',
        ),
        migrations.AddField(
            model_name='spot',
            name='about',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
