# Generated by Django 2.2.28 on 2024-03-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0005_auto_20240320_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='about',
            new_name='spotAbout',
        ),
    ]
