# Generated by Django 2.2.28 on 2024-03-22 14:02

from django.db import migrations, models
import django.db.models.deletion
import gregssnorkelscores.models


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0005_auto_20240322_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='spot',
            field=models.ForeignKey(default=gregssnorkelscores.models.Review.get_default_spot, on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.Spot'),
        ),
    ]
