# Generated by Django 2.2.28 on 2024-03-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0006_auto_20240320_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='location',
        ),
    ]
