# Generated by Django 4.2.11 on 2024-03-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0007_remove_spot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.location'),
        ),
    ]
