# Generated by Django 4.2.11 on 2024-03-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregssnorkelscores', '0008_spot_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name_plural': 'Spots'},
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spotAbout',
        ),
        migrations.AddField(
            model_name='location',
            name='about',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='reviewsAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='reviewsAverage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='spot',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gregssnorkelscores.location'),
        ),
    ]
